<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-RO7LUG0" failures="1" tests="4" name="WithdrawFundTest" time="16.677" errors="0" timestamp="2023-08-15T10:47:06 IST">
  <testcase classname="frontEndTesting.WithdrawFundTest" name="withdrawFundInPrimaryAccount" time="3.732"/>
  <testcase classname="frontEndTesting.WithdrawFundTest" name="withdrawFundInSavingAccount" time="2.021"/>
  <testcase classname="frontEndTesting.WithdrawFundTest" name="withdrawingAmountGreaterThanCurrentAmounForPrimaryAccount" time="1.81"/>
  <testcase classname="frontEndTesting.WithdrawFundTest" name="withdrawingAmountGreaterThanCurrentAmounForSavingsAccount" time="2.952">
    <failure type="java.lang.AssertionError" message="expected [Insufficient Funds] but found [Money Withdrawn successfully!!]">
      <![CDATA[java.lang.AssertionError: expected [Insufficient Funds] but found [Money Withdrawn successfully!!]
at frontEndTesting.WithdrawFundTest.withdrawingAmountGreaterThanCurrentAmounForSavingsAccount(WithdrawFundTest.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- withdrawingAmountGreaterThanCurrentAmounForSavingsAccount -->
</testsuite> <!-- WithdrawFundTest -->
